### ISSUE TITLE
build before deploying

### ISSUE THREAD

**Issue by verygoodsoftwarenotvirus** [dinnerdonebetter/dinnerdonebetter#987]
currently I just run `skaffold deploy`, which almost always spends a good 20 minutes building containers before attempting to deploy them. Surely I could build the containers in a prior step and re-use them, no? perhaps even in parallel?

fun fact: tried this recently. Building individual artifacts in skaffold? easy peasy. Getting `skaffold deploy` to know they exist and not build them all over again? eluded me.

**Comment by verygoodsoftwarenotvirus** [comment]
I _believe_ I had this mostly working in the following form:

```
---
concurrency:
  group: ${{ github.ref }}

on: [pull_request]
#  push:
#    branches:
#      - dev

name: deploy (dev)
jobs:
  changes:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      infra: ${{ steps.filter.outputs.infra }}
      backend: ${{ steps.filter.outputs.backend }}
      frontend_webapp: ${{ steps.filter.outputs.frontend_webapp }}
      frontend_landing: ${{ steps.filter.outputs.frontend_landing }}
      frontend_admin: ${{ steps.filter.outputs.frontend_admin }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - backend/**
            infra:
              - infra/**
            frontend_webapp:
              - frontend/apps/web/**
              - frontend/packages/**
              - frontend/environments/dev/webapp/**
            frontend_landing:
              - frontend/apps/landing/**
              - frontend/packages/**
              - frontend/environments/dev/landing/**
            frontend_admin:
              - frontend/apps/admin/**
              - frontend/packages/**
              - frontend/environments/dev/admin/**

  baseline-infra:
    needs: [changes]
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # these two steps should be commented out if the cluster hasn't been created yet
      - name: get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'dev'
          context_name: 'dev_context'
          location: 'us-central1'

      - name: copy kubeconfig
        working-directory: backend/deploy/environments/dev
        run: |
          cp ${{ env.KUBECONFIG }} terraform/terraform_kubeconfig

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}

      - name: Terraform Init
        working-directory: infra/deploy/environments/dev/terraform
        id: init
        run: terraform init

      - name: Terraform Validate
        working-directory: infra/deploy/environments/dev/terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra/deploy/environments/dev/terraform

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - backend/**
            frontend:
              - frontend/apps/**
              - frontend/packages/**
              - frontend/environments/dev/**
            frontend_webapp:
              - frontend/apps/web/**
              - frontend/packages/**
              - frontend/environments/dev/webapp/**
            frontend_landing:
              - frontend/apps/landing/**
              - frontend/packages/**
              - frontend/environments/dev/landing/**
            frontend_admin:
              - frontend/apps/admin/**
              - frontend/packages/**
              - frontend/environments/dev/admin/**

  backend-infra:
    needs:
      - changes
      - baseline-infra
    timeout-minutes: 90
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.backend == 'true' }}
    strategy:
      matrix:
        container-registry: ['us-central1-docker.pkg.dev']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push to pkg.dev
        run: gcloud auth configure-docker ${{ matrix.container-registry }}

      - name: get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'dev'
          context_name: 'dev_context'
          location: 'us-central1'

      - name: copy kubeconfig
        working-directory: backend/deploy/environments/dev
        run: |
          cp ${{ env.KUBECONFIG }} terraform/terraform_kubeconfig

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}

      - name: Terraform Init
        working-directory: backend/deploy/environments/dev/terraform
        id: init
        run: terraform init

      # validate backend workspace terraform

      - name: Terraform Validate
        working-directory: backend/deploy/environments/dev/terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: backend/deploy/environments/dev/terraform

      - name: remove kubernetes config
        working-directory: backend/deploy/environments/dev
        run: rm -f ${{ env.KUBECONFIG }} terraform/terraform_kubeconfig

  admin-webapp-infra:
    needs:
      - changes
      - baseline-infra
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.frontend_admin == 'true' }}
    strategy:
      matrix:
        configs:
          - gcp-region: 'us-central1'
            gcp-project: 'dinner-done-better-dev'
            container-name: 'admin_app_server'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'dev'
          context_name: 'dev_context'
          location: 'us-central1'

      - name: copy kubeconfig
        working-directory: frontend/deploy/environments/dev/admin
        run: |
          cp ${{ env.KUBECONFIG }} terraform/terraform_kubeconfig

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}

      - name: Terraform Init
        working-directory: frontend/deploy/environments/dev/admin/terraform
        id: init
        run: terraform init

      # validate backend workspace terraform

      - name: Terraform Format
        working-directory: frontend/deploy/environments/dev/admin/terraform
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: frontend/deploy/environments/dev/admin/terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: frontend/deploy/environments/dev/admin/terraform

  landing-infra:
    needs:
      - changes
      - baseline-infra
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.frontend_landing == 'true' }}
    strategy:
      matrix:
        configs:
          - gcp-region: 'us-central1'
            gcp-project: 'dinner-done-better-dev'
            container-name: 'landing_server'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}

      - name: Terraform Init
        working-directory: frontend/deploy/environments/dev/landing/terraform
        id: init
        run: terraform init

      - name: Terraform Format
        working-directory: frontend/deploy/environments/dev/landing/terraform
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: frontend/deploy/environments/dev/landing/terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: frontend/deploy/environments/dev/landing/terraform

  webapp-infra:
    needs:
      - changes
      - baseline-infra
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.frontend_webapp == 'true' }}
    strategy:
      matrix:
        configs:
          - gcp-region: 'us-central1'
            gcp-project: 'dinner-done-better-dev'
            container-name: 'webapp_server'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'dev'
          context_name: 'dev_context'
          location: 'us-central1'

      - name: copy kubeconfig
        working-directory: frontend/deploy/environments/dev/webapp
        run: |
          cp ${{ env.KUBECONFIG }} terraform/terraform_kubeconfig

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}

      - name: Terraform Init
        working-directory: frontend/deploy/environments/dev/webapp/terraform
        id: init
        run: terraform init

      - name: Terraform Format
        working-directory: frontend/deploy/environments/dev/webapp/terraform
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: frontend/deploy/environments/dev/webapp/terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: frontend/deploy/environments/dev/webapp/terraform

  build_containers:
    needs:
      - changes
    timeout-minutes: 60
    if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend_admin == 'true' || needs.changes.outputs.frontend_landing == 'true' || needs.changes.outputs.frontend_webapp == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container-registry: ['us-central1-docker.pkg.dev']
        artifact:
          - 'dinner-done-better-service-api'
          - 'dinner-done-better-job-db-cleaner'
          - 'dinner-done-better-job-email-prober'
          - 'dinner-done-better-job-meal-plan-finalizer'
          - 'dinner-done-better-job-meal-plan-grocery-list-init'
          - 'dinner-done-better-job-meal-plan-task-creator'
          - 'dinner-done-better-job-search-data-index-scheduler'
          - 'dinner-done-better-async-message-handler'
          - 'dinner-done-better-webapp'
          - 'dinner-done-better-admin-app'
          - 'dinner-done-better-landing'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push to pkg.dev
        run: gcloud auth configure-docker pkg.dev

      - name: setup Skaffold
        run: gcloud components update && gcloud components install skaffold

      - name: Skaffold build
        working-directory: backend
        run: skaffold build --push=true --build-image=${{ matrix.artifact }} --profile=dev --file-output=build-${{ matrix.artifact }}.json

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: skaffold-builds-${{ matrix.artifact }}
          path: backend/build-${{ matrix.artifact }}.json

  applications:
    if: always() && !failure() && !cancelled()
    needs:
      - backend-infra
      - webapp-infra
      - admin-webapp-infra
      - landing-infra
      - build_containers
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container-registry: ['us-central1-docker.pkg.dev']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push to pkg.dev
        run: gcloud auth configure-docker ${{ matrix.container-registry }}

      - name: get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'dev'
          context_name: 'dev_context'
          location: 'us-central1'

      - name: setup Skaffold
        run: gcloud components update && gcloud components install skaffold

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: skaffold-builds-*
          path: skaffold_builds

      - name: Combine build files with jq
        run: |
          # Merge all build-*.json into a single combined-build.json
          jq -n '{ builds: [inputs.builds] | add }' skaffold_builds/build-*.json > combined-build.json

      - name: deploy kubernetes prerequisites
        run: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml

      - name: deploy services
        run: |
          skaffold deploy --filename=skaffold.yaml --profile dev --build-artifacts=combined-build.json \
            --images us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-service-api \
            --images us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-db-cleaner \
            --images us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-email-prober \
            --images us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-meal-plan-finalizer \
            --images us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-meal-plan-grocery-list-init \
            --images us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-meal-plan-task-creator \
            --images us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-job-search-data-index-scheduler \
            --images us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-async-message-handler \
            --images us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-webapp \
            --images us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-admin-app \
            --images us-central1-docker.pkg.dev/dinner-done-better-dev/containers/dinner-done-better-landing

      # remove some files so they don't end up in any post-Action zip folders or whatever

      - name: remove skaffold builds
        run: rm -rf skaffold_builds

      - name: remove kubernetes config
        working-directory: backend/deploy/environments/dev
        run: rm -f ${{ env.KUBECONFIG }} skaffold_builds
```
